# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: api_development
  pool: 5
  host: localhost
  timeout: 5000
  username: postgres
  password: Password1!

