# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 053f62402d3c8f789c83a727bc974abde0d4f540c2da81f6d4dde47a242e0af371f3d3de059c6564a2e65f6ab2bf270926c45a4cdcc99674baf33dc3bbd027fc

test:
  secret_key_base: 8f5345ad2e472bf6b2a3cc719bc9996cf49febea816fa739b351c310ae51b7a1d8bb68cb7971ea59beab9e278a66f9cd1c29a1bb54428f7cf063ff45b8d6f562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
