# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e0d3bc8d2fc6d4ca52f094b0a506de377de80c68c5a7b6fa8d9a4781ac6bd4e8a5f6bcfe86690c5bc514bc87abd508e8e1208dbc6131531de9f155fc0c921c7

test:
  secret_key_base: 19a417e8d4ad26d271b08b14d5f5191d4d8194b6629270f239ba4b4d1b7efbb7585b61022155b6a9452c1985ed02bac5cdb4765f4f8a683ecb973512ab80e0e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
